routes/web.php
<?php

use App\Http\Controllers\Frontend\Auth\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('index');
//});
Route::group(
    [
        'as' => 'user.',
        'middleware' => ['guest:web'],
    ],
    function () {
        Route::get('/user/login', [LoginController::class, 'showLoginForm'])->name('showLoginForm');
        Route::post('/user/login', [LoginController::class, 'attemptLogin'])->name('login');
    }
);

Route::group(
    [
        'as' => 'user.',
        'middleware' => ['auth:web'],
    ],
    function () {
        Route::get('/clubs/create', 'ClubController@showFormCreate')->name('clubs.showFormCreate');
        Route::post('/clubs/create', 'ClubController@store')->name('clubs.store');
        Route::get('/tournaments/create', 'TournamentController@showFormCreate')->name('tournaments.showFormCreate');
        Route::get('/tournaments/dashboard', 'TournamentController@index')->name('tournaments.index');
        Route::get('/tournaments/setting', 'TournamentController@setting')->name('tournaments.setting');
        Route::get('/tournaments/status', 'TournamentController@showStatusTournament')->name('tournaments.status');
        Route::get('/tournaments/clubs', 'TournamentController@showListClub')->name('tournaments.clubs');
        Route::get('/tournaments/sort-league', 'TournamentController@showLeague')->name('tournaments.sortLeague');
        Route::get('/tournaments/sort-match-pair', 'TournamentController@showMatchPair')->name('tournaments.sortMatchPair');
        Route::get('/tournaments/schedule', 'TournamentController@showSchedule')->name('tournaments.showSchedule');
        Route::get('/tournaments/knock-out', 'TournamentController@showKnockOut')->name('tournaments.showKnockOut');
        Route::get('/tournaments/group-stage', 'TournamentController@showGroupStage')->name('tournaments.showGroupStage');
        Route::get('/tournaments/chart', 'TournamentController@showChart')->name('tournaments.showChart');
        Route::get('/user/logout', [LoginController::class,'logout'])->name('logout-user');
        Route::get('/user/management-club', 'UserController@showManagementClub')->name('showManagementClub');
        Route::get('/user/management', 'UserController@showAllManagement')->name('showAllManagement');
        Route::get('/user/management-member', 'UserController@showMemberInClub')->name('showMemberInClub');
        Route::get('/user/management-tournament', 'UserController@showTournamentOfClub')->name('showTournamentOfClub');
        Route::get('/user/achievement-statistics', 'UserController@showStatistic')->name('showStatistic');
    }
);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/clubs/search', 'ClubController@showFormSearch')->name('clubs.showFormSearch');
Route::get('/tournaments/search', 'TournamentController@showFormSearch')->name('tournaments.showFormSearch');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class UserController
 * @package App\Http\Controllers
 */
class UserController extends Controller
{
    public function showManagementClub()
    {
        return view('frontend.users.management-club');
    }

    public function showAllManagement()
    {
        return view('frontend.users.management-all');
    }

    public function showMemberInClub()
    {
        return view('frontend.users.management-member-in-club');
    }

    public function showTournamentOfClub()
    {
        return view('frontend.users.management-tournament');
    }

    public function showStatistic()
    {
        return view('frontend.users.achievement-statistics');
    }
}

resources/views/frontend/users/includes/modal-create-member.blade.php
<div class="modal fade" id="createMemberClub" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm thành viên</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div id="editProfileMember" class="editProfileMember">
                        <form method="POST" class="form-update-player-member">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-5 col-sm-12 col-xs-12 personal-avatar">
                                        <div class="avatar-container d-flex align-items-center justify-content-center">
                                            <div class="avatar-position">
                                                <img src="{{asset('image/team.png')}}">
                                            </div>
                                        </div>
                                        <hr class="hidden-md hidden-lg">
                                        <div class="row d-flex align-items-center justify-content-center wrap-card">
                                            <label class="title"><b>Ảnh thẻ căn cước</b></label>
                                            <div class="avatar-card col-md-12 col-sm-12 col-xs-12 mb-5">
                                                <span class="title-card mb-3">Mặt trước:</span>
                                                <img src="{{asset('image/team.png')}}">
                                            </div>
                                            <div class="avatar-card col-md-12 col-sm-12 col-xs-12">
                                                <span class="title-card mb-3">Mặt sau:</span>
                                                <img src="{{asset('image/team.png')}}">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- edit form column -->
                                    <div class="col-md-7 col-sm-12 col-xs-12 personal-info mt-15">
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label required">Họ tên đầy đủ</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control fullname" name="fullname" type="text" value="Lê Duy Thành">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12  control-label">Tên thi đấu<span class="text-red">*</span></label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control namePlayer" name="namePlayer" type="text">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Số áo<span class="text-red">*</span></label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control numberPlayer" name="numberPlayer" type="text">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Vị trí thi đấu</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <select class="form-control text-capitalize player_position" name="position">
                                                    <option value="" selected="selected">-- Vui lòng chọn --</option>
                                                    <option value="1">thủ môn</option>
                                                    <option value="2">hậu vệ</option>
                                                    <option value="3">tiền vệ</option>
                                                    <option value="4">tiền đạo</option>
                                                    <option value="5">khác</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Vai trò</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <select class="form-control text-capitalize role" name="role">
                                                    <option selected="selected" value="1">Vận Động Viên</option>
                                                    <option value="2">Ông Bầu</option>
                                                    <option value="3">Lãnh Đội</option>
                                                    <option value="4" >HLV Trưởng</option>
                                                    <option value="5">Trợ Lý HLV</option>
                                                    <option value="6">HLV Thủ Môn</option>
                                                    <option value="7">HLV Thể Lực</option>
                                                    <option value="8">Đội Trưởng</option>
                                                    <option value="9">Đội Phó</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Điện Thoại</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control phone" name="phone" type="text">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Ngày sinh</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="width200 form-control datepickerBirthday hasDatepicker" title="Ngày sinh" name="birthday" type="text" value="" id="dp1605932411550">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Địa chỉ Email</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control" title="Địa chỉ email" name="email" type="email">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 col-sm-12 col-xs-12 mt-15 hidden-xs hidden-sm">
                                    </div>
                                    <div class="col-md-6 col-sm-12 col-xs-12 form-group display-align text-right wrapButtonFooter">
                                        <button class="btn btn-secondary" data-dismiss="modal" type="reset">
                                            Đóng                                    </button>
                                        <button class="btn btn-success save submit-update-player-register" type="submit">
                                            Lưu                                    </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/users/includes/modal-delete-member.blade.php
<div class="modal fade" id="deleteMember" tabindex="-1" role="dialog" aria-labelledby="deleteMember" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="text-center">
                    <h2 class="mb-4">Xác nhận</h2>
                    <h5>Bạn có chắc muốn xóa thành viên này khỏi ?</h5>
                </div>

                <div class="text-center mt-4">
                    <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal">Hủy bỏ</button>
                    <button type="button" class="btn btn-danger ml-2">Đồng ý</button>
                </div>

            </div>
        </div>
    </div>
</div>

resources/views/frontend/users/includes/modal-detail-member.blade.php
<div class="modal fade" id="detailMemberClub" tabindex="-1" role="dialog" aria-labelledby="detailMemberClub" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thông tin chi tiết</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <div id="editProfileMember" class="editProfileMember">
                        <form method="POST" class="form-update-player-member">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-5 col-sm-12 col-xs-12 personal-avatar">
                                        <div class="avatar-container d-flex align-items-center justify-content-center">
                                            <div class="avatar-position">
                                                <img src="{{asset('image/team.png')}}">
                                            </div>
                                        </div>
                                        <hr class="hidden-md hidden-lg">
                                        <div class="row d-flex align-items-center justify-content-center wrap-card">
                                            <label class="title"><b>Ảnh thẻ căn cước</b></label>
                                            <div class="avatar-card col-md-12 col-sm-12 col-xs-12 mb-5">
                                                <span class="title-card mb-3">Mặt trước:</span>
                                                <img src="{{asset('image/team.png')}}">
                                            </div>
                                            <div class="avatar-card col-md-12 col-sm-12 col-xs-12">
                                                <span class="title-card mb-3">Mặt sau:</span>
                                                <img src="{{asset('image/team.png')}}">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- edit form column -->
                                    <div class="col-md-7 col-sm-12 col-xs-12 personal-info mt-15">
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label required">Họ tên đầy đủ</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control fullname" name="fullname" type="text" value="Lê Duy Thành">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12  control-label ">Tên thi đấu</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control namePlayer" name="namePlayer" type="text">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label ">Số áo</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control numberPlayer" name="numberPlayer" type="text">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Vị trí </label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <select class="form-control text-capitalize player_position" name="position"><option value="" selected="selected">-- Vui lòng chọn --</option><option value="1">thủ môn</option><option value="2">hậu vệ</option><option value="3">tiền vệ</option><option value="4">tiền đạo</option><option value="5">khác</option></select>
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Vai trò</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <select class="form-control text-capitalize role" name="role"><option value="1">Vận Động Viên</option><option value="2">Ông Bầu</option><option value="3">Lãnh Đội</option><option value="4" selected="selected">HLV Trưởng</option><option value="5">Trợ Lý HLV</option><option value="6">HLV Thủ Môn</option><option value="7">HLV Thể Lực</option><option value="8">Đội Trưởng</option><option value="9">Đội Phó</option></select>
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Điện Thoại</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control phone" name="phone" type="text">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Ngày sinh</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="width200 form-control datepickerBirthday hasDatepicker" title="Ngày sinh" name="birthday" type="text" value="" id="dp1605932411550">
                                            </div>
                                        </div>
                                        <div class="form-group display-align">
                                            <label class="col-12 control-label">Địa chỉ Email</label>
                                            <div class="col-lg-9 col-md-9 col-sm-8">
                                                <input class="form-control" title="Địa chỉ email" name="email" type="email">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 col-sm-12 col-xs-12 mt-15 hidden-xs hidden-sm">
                                    </div>
                                    <div class="col-md-6 col-sm-12 col-xs-12 form-group display-align text-right wrapButtonFooter">
                                        <button class="btn btn-secondary" data-dismiss="modal" type="reset">
                                            Đóng
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/users/includes/sidebar.blade.php
<div class="layout-sidenav-nav">
    <nav class="sb-sidenav sb-sidenav-dark">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <a class="nav-link nav-link-user collapsed" href="{{route('user.showManagementClub')}}">
                    <i class="fa fa-credit-card mr-2"></i>
                    Thông tin đội
                </a>

                <a class="nav-link nav-link-character collapsed" href="{{route('user.showManagementClub')}}">
                    <i class="fa fa-cog mr-2"></i>
                    Chỉnh sửa đội
                </a>
                <a class="nav-link nav-link-deposit-and-payment collapsed" href="{{route('user.showMemberInClub')}}">
                    <i class="fa fa-users mr-2"></i>
                    Thành viên đội
                </a>

                <a class="nav-link nav-link-various-setting collapsed" href="{{route('user.showTournamentOfClub')}}">
                    <i class="far fa-futbol mr-2"></i>
                    Các giải đấu
                </a>

                <a class="nav-link nav-link-gacha collapsed" href="{{route('user.showStatistic')}}">
                    <i class="far fa-chart-bar mr-2"></i>
                    Thống kê
                </a>
            </div>
        </div>
    </nav>
</div>