routes/web.php
<?php

use App\Http\Controllers\Frontend\Auth\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('index');
//});
Route::group(
    [
        'as' => 'user.',
        'middleware' => ['guest:web'],
    ],
    function () {
        Route::get('/user/login', [LoginController::class, 'showLoginForm'])->name('showLoginForm');
        Route::post('/user/login', [LoginController::class, 'attemptLogin'])->name('login');
    }
);

Route::group(
    [
        'as' => 'user.',
        'middleware' => ['auth:web'],
    ],
    function () {
        Route::get('/clubs/create', 'ClubController@showFormCreate')->name('clubs.showFormCreate');
        Route::post('/clubs/create', 'ClubController@store')->name('clubs.store');
        Route::get('/tournaments/create', 'TournamentController@showFormCreate')->name('tournaments.showFormCreate');
        Route::get('/tournaments/dashboard', 'TournamentController@index')->name('tournaments.index');
        Route::get('/tournaments/setting', 'TournamentController@setting')->name('tournaments.setting');
        Route::get('/tournaments/status', 'TournamentController@showStatusTournament')->name('tournaments.status');
        Route::get('/tournaments/clubs', 'TournamentController@showListClub')->name('tournaments.clubs');
        Route::get('/tournaments/sort-league', 'TournamentController@showLeague')->name('tournaments.sortLeague');
        Route::get('/tournaments/sort-match-pair', 'TournamentController@showMatchPair')->name('tournaments.sortMatchPair');
        Route::get('/tournaments/schedule', 'TournamentController@showSchedule')->name('tournaments.showSchedule');
        Route::get('/tournaments/knock-out', 'TournamentController@showKnockOut')->name('tournaments.showKnockOut');
        Route::get('/tournaments/group-stage', 'TournamentController@showGroupStage')->name('tournaments.showGroupStage');
        Route::get('/tournaments/chart', 'TournamentController@showChart')->name('tournaments.showChart');
        Route::get('/user/logout', [LoginController::class,'logout'])->name('logout-user');
        Route::get('/user/management-club', 'UserController@showManagementClub')->name('showManagementClub');
        Route::get('/user/management', 'UserController@showAllManagement')->name('showAllManagement');
        Route::get('/user/management-member', 'UserController@showMemberInClub')->name('showMemberInClub');
        Route::get('/user/management-tournament', 'UserController@showTournamentOfClub')->name('showTournamentOfClub');
        Route::get('/user/achievement-statistics', 'UserController@showStatistic')->name('showStatistic');
    }
);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/clubs/search', 'ClubController@showFormSearch')->name('clubs.showFormSearch');
Route::get('/tournaments/search', 'TournamentController@showFormSearch')->name('tournaments.showFormSearch');

app/Models/Club.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Club extends Model
{
    use Notifiable,
        SoftDeletes;

    protected $table = 'clubs';

    protected $fillable = [
        'user_id',
        'name',
        'avatar',
        'level',
        'telephone_number',
        'gender',
        'status',
        'age',
        'time_activity',
        'area',
        'uniform',
        'introduce',
        'page_club',
    ];

    //----- Relationship -----//
}

app/Http/Controllers/Frontend/ClubController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Frontend\Clubs\CreateClubRequest;
use App\Repositories\ClubRepository\ClubRepositoryInterface;
use App\Services\ClubService\CreateClubService;
use Illuminate\Http\Request;

/**
 * Class ClubController
 * @package App\Http\Controllers
 */
class ClubController extends Controller
{
    private $clubRepository;

    /**
     * ClubController constructor.
     * @param ClubRepositoryInterface $clubRepository
     */
    public function __construct(
        ClubRepositoryInterface $clubRepository
    )
    {
        $this->clubRepository = $clubRepository;
    }

    public function showFormCreate()
    {
        return view('frontend.clubs.create');
    }

    public function store(Request $createClubRequest, CreateClubService $createClubService)
    {
        $data = $createClubService->handle($createClubRequest->except('_token'));

        $this->clubRepository->create($data);
    }

    public function showFormSearch()
    {
        return view('frontend.clubs.search');
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    public function index()
    {
        return view('frontend.index');
    }
}

app/Http/Controllers/Frontend/TournamentController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class TournamentController
 * @package App\Http\Controllers
 */
class TournamentController extends Controller
{
    public function showFormCreate()
    {
        return view('frontend.tournaments.create');
    }

    public function showFormSearch()
    {
        return view('frontend.tournaments.search');
    }

    public function index()
    {
        return view('frontend.tournaments.index');
    }

    public function setting()
    {
        return view('frontend.tournaments.setting');
    }

    public function showStatusTournament()
    {
        return view('frontend.tournaments.status');
    }

    public function showListClub()
    {
        return view('frontend.tournaments.club');
    }

    public function showLeague()
    {
        return view('frontend.tournaments.sort-league');
    }

    public function showMatchPair()
    {
        return view('frontend.tournaments.sort-match-pair');
    }

    public function showSchedule()
    {
        return view('frontend.tournaments.schedule');
    }

    public function showGroupStage()
    {
        return view('frontend.tournaments.group-stage');
    }

    public function showKnockOut()
    {
        return view('frontend.tournaments.knockout');
    }

    public function showChart()
    {
        return view('frontend.tournaments.chart');
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class UserController
 * @package App\Http\Controllers
 */
class UserController extends Controller
{
    public function showManagementClub()
    {
        return view('frontend.users.management-club');
    }

    public function showAllManagement()
    {
        return view('frontend.users.management-all');
    }

    public function showMemberInClub()
    {
        return view('frontend.users.management-member-in-club');
    }

    public function showTournamentOfClub()
    {
        return view('frontend.users.management-tournament');
    }

    public function showStatistic()
    {
        return view('frontend.users.achievement-statistics');
    }
}

resources/views/frontend/clubs/create.blade.php
@extends('frontend.layouts.app')

@section('content')
    <div class="create-club mb-3">
        <div class="container-fluid d-flex align-items-center justify-content-center">
            <div class="col-sm-9">
                <div class="card">
                    <div class="card-header">
                        Tạo đội
                        <div class="message-require">Vui lòng nhập thông tin hợp lệ cho các trường được yêu cầu <span class="text-red">*</span></div>
                    </div>
                    <form accept-charset="UTF-8" action="{{route('user.clubs.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">

                            <div class="frame-register">
                                <div class="row">
                                    <div class="col-sm-5">
                                        <label for="exampleInputEmail1">Ảnh đại diện</label>
                                        <div class="logo-club">
                                            <img class="icon-logo" width="242" height="242" src="{{asset('image/team.png')}}">
                                        </div>

                                        <div class="input-group mt-3 mb-3">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" id="upload-logo" name="avatar">
                                                <label class="custom-file-label" for="logo">Logo đội của bạn</label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-7">
                                        <form>
                                            <div class="form-group">
                                                <label for="name">Tên đội<span class="text-red">*</span></label>
                                                <input type="text" class="form-control" id="name" name="name" placeholder="Tên đội của bạn">
                                            </div>
                                            <div class="form-group">
                                                <label for="level">Trình độ<span class="text-red">*</span></label>
                                                <select class="form-control" id="level" name="level">
                                                    <option value="">Vui lòng chọn</option>
                                                    <option value="4">Chuyên nghiệp</option>
                                                    <option value="3">Bán chuyên nghiệp</option>
                                                    <option value="2">Trung cấp</option>
                                                    <option value="1">Vui khoẻ</option>
                                                    <option value="0">Khác</option>
                                                </select>
                                            </div>
                                            <div class="form-group-inline">
                                                <div class="row">
                                                    <div class="col-sm-8">
                                                        <div class="form-group">
                                                            <label for="telephone_number">Số điện thoại<span class="text-red">*</span></label>
                                                            <input type="text" name="telephone_number" class="form-control" id="telephone_number" placeholder="Số điện thoại">
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-4">
                                                        <div class="form-group">
                                                            <label for="status">Chế độ</label>
                                                            <select class="form-control" id="status" name="status">
                                                                <option value="1">Công khai</option>
                                                                <option value="0">Bí mật</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="gender">Giới tính<span class="text-red">*</span></label>
                                                <select class="form-control" id="gender" name="gender">
                                                    <option value="">Vui lòng chọn</option>
                                                    <option value="0">Nam</option>
                                                    <option value="1">Nữ</option>
                                                </select>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <div class="frame-register">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="email">Địa chỉ email</label>
                                            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="name_contact">Tên người liên hệ</label>
                                            <input type="text" name="people_contact" class="form-control" id="people_contact" placeholder="Tên người liên hệ">
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="age">Độ tuổi</label>
                                            <select class="form-control" id="age" name="age">
                                                <option value="">Vui lòng chọn</option>
                                                <option value="0">15-20</option>
                                                <option value="1">20-25</option>
                                                <option value="2">25-30</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group-inline col-sm-12">
                                        <div class="row">
                                            <div class="col-sm-4">
                                                <div class="form-group">
                                                    <label for="area">Khu vực hoạt động</label>
                                                    <input type="text" class="form-control" id="area" name="area" placeholder="Nhập vị trí">
                                                </div>
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="form-group">
                                                    <label for="time_active">Khung thời gian hoạt động</label>
                                                    <input type="text" class="form-control" id="time_active" name="time_activity" placeholder="VD: T2-07:23 hoặc CN-18:23">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="frame-register">
                                <div class="row">
                                    <div class="col-sm-4"></div>
                                    <div class="col-sm-4">
                                        <label for="exampleFormControlSelect1">Đồng phục</label>
                                        <div class="logo-club mb-3">
                                            <img class="icon-uniform" width="242" height="242" src="{{asset('image/shirt.svg')}}">
                                        </div>
                                        <div class="input-group mb-3">
                                            <div class="custom-file">
                                                <input name="uniform" type="file" class="custom-file-input" id="uploadUniform">
                                                <label class="custom-file-label" for="uploadUniform">Đồng phục đội</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4"></div>
                                </div>
                            </div>

                            <div class="last-register">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="introduce">Giới thiệu về đội </label>
                                            <textarea name="introduce" class="form-control" id="introduce" placeholder="Lời giới thiệu về đội"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="frame-register text-center border-bottom-0">
                                <button type="submit" class="btn btn-success">Lưu</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/clubs/search.blade.php
@extends('frontend.layouts.app')

@section('content')
    <div class="search-club mb-3">
        <div class="container-fluid">
            <div class="row form-search">
                <div class="col-sm-5">
                    <div class="input-group">
                        <input class="form-control" placeholder="Tên giải đấu, tên người quản lý" name="keyword" type="text">
                        <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                            </span>
                    </div>
                </div>

                <div class="col-sm-7">
                    <div class="row">
                        <div class="col-sm-4">
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <select class="form-control" id="exampleFormControlSelect1">
                                    <option>Trình độ</option>
                                    <option>Chuyên nghiệp</option>
                                    <option>Bán chuyên nghiệp</option>
                                    <option>Trung cấp</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <select class="form-control" id="exampleFormControlSelect1">
                                    <option>Giới tính</option>
                                    <option>Nam</option>
                                    <option>Nữ</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row result-search-club">
                <div class="col-sm-12 col-md-3 mb-3">
                    <div class="club">
                        <div class="avatar-club mb-2">
                            <a href="#">
                                <img class="w-100" src="{{asset('image/team.png')}}" alt="avatar-club">
                            </a>
                        </div>
                        <a href="#" class="name-club">GBG</a>
                        <div>Trinh do || Gioi tinh</div>
                        <div class="member-club">
                            <div>Thanh vien</div>
                            <div class="flex-item">
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 col-md-3 mb-3">
                    <div class="club">
                        <div class="avatar-club mb-2">
                            <a href="#">
                                <img class="w-100" src="{{asset('image/team.png')}}" alt="avatar-club">
                            </a>
                        </div>
                        <a href="#" class="name-club">GBG</a>
                        <div>Trinh do || Gioi tinh</div>
                        <div class="member-club">
                            <div>Thanh vien</div>
                            <div class="flex-item">
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-3 mb-3">
                    <div class="club">
                        <div class="avatar-club mb-2">
                            <a href="#">
                                <img class="w-100" src="{{asset('image/team.png')}}" alt="avatar-club">
                            </a>
                        </div>
                        <a href="#" class="name-club">GBG</a>
                        <div>Trinh do || Gioi tinh</div>
                        <div class="member-club">
                            <div>Thanh vien</div>
                            <div class="flex-item">
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-3 mb-3">
                    <div class="club">
                        <div class="avatar-club mb-2">
                            <a href="#">
                                <img class="w-100" src="{{asset('image/team.png')}}" alt="avatar-club">
                            </a>
                        </div>
                        <a href="#" class="name-club">GBG</a>
                        <div>Trinh do || Gioi tinh</div>
                        <div class="member-club">
                            <div>Thanh vien</div>
                            <div class="flex-item">
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                                <div class="member">
                                    <img width="38" height="38" src="{{asset('image/team.png')}}" alt="avatar-member">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection