routes/web.php
<?php

use App\Http\Controllers\Frontend\Auth\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('index');
//});
Route::group(
    [
        'as' => 'user.',
        'middleware' => ['guest:web'],
    ],
    function () {
        Route::get('/user/login', [LoginController::class, 'showLoginForm'])->name('showLoginForm');
        Route::post('/user/login', [LoginController::class, 'attemptLogin'])->name('login');
    }
);

Route::group(
    [
        'as' => 'user.',
        'middleware' => ['auth:web'],
    ],
    function () {
        Route::get('/clubs/create', 'ClubController@showFormCreate')->name('clubs.showFormCreate');
        Route::post('/clubs/create', 'ClubController@store')->name('clubs.store');
        Route::get('/tournaments/create', 'TournamentController@showFormCreate')->name('tournaments.showFormCreate');
        Route::get('/tournaments/dashboard', 'TournamentController@index')->name('tournaments.index');
        Route::get('/tournaments/setting', 'TournamentController@setting')->name('tournaments.setting');
        Route::get('/tournaments/status', 'TournamentController@showStatusTournament')->name('tournaments.status');
        Route::get('/tournaments/clubs', 'TournamentController@showListClub')->name('tournaments.clubs');
        Route::get('/tournaments/sort-league', 'TournamentController@showLeague')->name('tournaments.sortLeague');
        Route::get('/tournaments/sort-match-pair', 'TournamentController@showMatchPair')->name('tournaments.sortMatchPair');
        Route::get('/tournaments/schedule', 'TournamentController@showSchedule')->name('tournaments.showSchedule');
        Route::get('/tournaments/knock-out', 'TournamentController@showKnockOut')->name('tournaments.showKnockOut');
        Route::get('/tournaments/group-stage', 'TournamentController@showGroupStage')->name('tournaments.showGroupStage');
        Route::get('/tournaments/chart', 'TournamentController@showChart')->name('tournaments.showChart');
        Route::get('/user/logout', [LoginController::class,'logout'])->name('logout-user');
        Route::get('/user/management-club', 'UserController@showManagementClub')->name('showManagementClub');
        Route::get('/user/management', 'UserController@showAllManagement')->name('showAllManagement');
        Route::get('/user/management-member', 'UserController@showMemberInClub')->name('showMemberInClub');
        Route::get('/user/management-tournament', 'UserController@showTournamentOfClub')->name('showTournamentOfClub');
        Route::get('/user/achievement-statistics', 'UserController@showStatistic')->name('showStatistic');
    }
);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/clubs/search', 'ClubController@showFormSearch')->name('clubs.showFormSearch');
Route::get('/tournaments/search', 'TournamentController@showFormSearch')->name('tournaments.showFormSearch');

app/Http/Controllers/Frontend/ClubController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Frontend\Clubs\CreateClubRequest;
use App\Repositories\ClubRepository\ClubRepositoryInterface;
use App\Services\ClubService\CreateClubService;
use Illuminate\Http\Request;

/**
 * Class ClubController
 * @package App\Http\Controllers
 */
class ClubController extends Controller
{
    private $clubRepository;

    /**
     * ClubController constructor.
     * @param ClubRepositoryInterface $clubRepository
     */
    public function __construct(
        ClubRepositoryInterface $clubRepository
    )
    {
        $this->clubRepository = $clubRepository;
    }

    public function showFormCreate()
    {
        return view('frontend.clubs.create');
    }

    public function store(Request $createClubRequest, CreateClubService $createClubService)
    {
        $data = $createClubService->handle($createClubRequest->except('_token'));

        $this->clubRepository->create($data);
    }

    public function showFormSearch()
    {
        return view('frontend.clubs.search');
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    public function index()
    {
        return view('frontend.index');
    }
}

app/Http/Controllers/Frontend/TournamentController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class TournamentController
 * @package App\Http\Controllers
 */
class TournamentController extends Controller
{
    public function showFormCreate()
    {
        return view('frontend.tournaments.create');
    }

    public function showFormSearch()
    {
        return view('frontend.tournaments.search');
    }

    public function index()
    {
        return view('frontend.tournaments.index');
    }

    public function setting()
    {
        return view('frontend.tournaments.setting');
    }

    public function showStatusTournament()
    {
        return view('frontend.tournaments.status');
    }

    public function showListClub()
    {
        return view('frontend.tournaments.club');
    }

    public function showLeague()
    {
        return view('frontend.tournaments.sort-league');
    }

    public function showMatchPair()
    {
        return view('frontend.tournaments.sort-match-pair');
    }

    public function showSchedule()
    {
        return view('frontend.tournaments.schedule');
    }

    public function showGroupStage()
    {
        return view('frontend.tournaments.group-stage');
    }

    public function showKnockOut()
    {
        return view('frontend.tournaments.knockout');
    }

    public function showChart()
    {
        return view('frontend.tournaments.chart');
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class UserController
 * @package App\Http\Controllers
 */
class UserController extends Controller
{
    public function showManagementClub()
    {
        return view('frontend.users.management-club');
    }

    public function showAllManagement()
    {
        return view('frontend.users.management-all');
    }

    public function showMemberInClub()
    {
        return view('frontend.users.management-member-in-club');
    }

    public function showTournamentOfClub()
    {
        return view('frontend.users.management-tournament');
    }

    public function showStatistic()
    {
        return view('frontend.users.achievement-statistics');
    }
}

resources/views/frontend/includes/footer.blade.php
<div id="copyright">
    <span>&copy; copyright 2020 by lan.tt166330@sis.hust.edu.vn</span>
</div>

resources/views/frontend/includes/header.blade.php
<div class="header-base">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="navbrand">
            <h1><a href="./index.html" class="brand">LEAGUE</a></h1>
            <div class="burger" id="burger">
			<span class="burger-open">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="16">
					<g fill="#fff" fill-rule="evenodd">
						<path d="M0 0h24v2H0zM0 7h24v2H0zM0 14h24v2H0z"/>
					</g>
				</svg>
			</span>
                <span class="burger-close">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20">
					<path fill="#fff" fill-rule="evenodd"
                          d="M17.778.808l1.414 1.414L11.414 10l7.778 7.778-1.414 1.414L10 11.414l-7.778 7.778-1.414-1.414L8.586 10 .808 2.222 2.222.808 10 8.586 17.778.808z"/>
				</svg>
			</span>
            </div>
        </div>
        <ul class="menu" id="menu">
            <li class="menu-item"><a href="{{route('home')}}" class="menu-link">Trang chủ</a></li>
            <li class="menu-item"><a href="{{route('clubs.showFormSearch')}}" class="menu-link">Tìm đội</a></li>
            <li class="menu-item"><a href="{{route('tournaments.showFormSearch')}}" class="menu-link">Tìm giải đấu</a>
            </li>

            @if (Auth::check())
                <li class="menu-item"><a href="{{route('user.tournaments.showFormCreate')}}" class="menu-link">Tạo giải
                        đấu</a></li>
                <li class="menu-item"><a href="{{route('user.clubs.showFormCreate')}}" class="menu-link">Tạo đội</a></li>
                <li class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                        Welcome, User <b class="caret"></b>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right position-absolute" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            @else
                <li class="menu-item"><a href="{{route('user.showLoginForm')}}" class="menu-link">Đăng nhập</a></li>
                <li class="menu-item"><a href="#" class="menu-link">Đăng ký</a></li>
            @endif
        </ul>
    </nav>
</div>