routes/web.php
<?php

use App\Http\Controllers\Frontend\Auth\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('index');
//});
Route::group(
    [
        'as' => 'user.',
        'middleware' => ['guest:web'],
    ],
    function () {
        Route::get('/user/login', [LoginController::class, 'showLoginForm'])->name('showLoginForm');
        Route::post('/user/login', [LoginController::class, 'attemptLogin'])->name('login');
    }
);

Route::group(
    [
        'as' => 'user.',
        'middleware' => ['auth:web'],
    ],
    function () {
        Route::get('/clubs/create', 'ClubController@showFormCreate')->name('clubs.showFormCreate');
        Route::post('/clubs/create', 'ClubController@store')->name('clubs.store');
        Route::get('/tournaments/create', 'TournamentController@showFormCreate')->name('tournaments.showFormCreate');
        Route::get('/tournaments/dashboard', 'TournamentController@index')->name('tournaments.index');
        Route::get('/tournaments/setting', 'TournamentController@setting')->name('tournaments.setting');
        Route::get('/tournaments/status', 'TournamentController@showStatusTournament')->name('tournaments.status');
        Route::get('/tournaments/clubs', 'TournamentController@showListClub')->name('tournaments.clubs');
        Route::get('/tournaments/sort-league', 'TournamentController@showLeague')->name('tournaments.sortLeague');
        Route::get('/tournaments/sort-match-pair', 'TournamentController@showMatchPair')->name('tournaments.sortMatchPair');
        Route::get('/tournaments/schedule', 'TournamentController@showSchedule')->name('tournaments.showSchedule');
        Route::get('/tournaments/knock-out', 'TournamentController@showKnockOut')->name('tournaments.showKnockOut');
        Route::get('/tournaments/group-stage', 'TournamentController@showGroupStage')->name('tournaments.showGroupStage');
        Route::get('/tournaments/chart', 'TournamentController@showChart')->name('tournaments.showChart');
        Route::get('/user/logout', [LoginController::class,'logout'])->name('logout-user');
        Route::get('/user/management-club', 'UserController@showManagementClub')->name('showManagementClub');
        Route::get('/user/management', 'UserController@showAllManagement')->name('showAllManagement');
        Route::get('/user/management-member', 'UserController@showMemberInClub')->name('showMemberInClub');
        Route::get('/user/management-tournament', 'UserController@showTournamentOfClub')->name('showTournamentOfClub');
        Route::get('/user/achievement-statistics', 'UserController@showStatistic')->name('showStatistic');
    }
);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/clubs/search', 'ClubController@showFormSearch')->name('clubs.showFormSearch');
Route::get('/tournaments/search', 'TournamentController@showFormSearch')->name('tournaments.showFormSearch');

app/Models/Tournament.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Tournament extends Model
{
    use Notifiable,
        SoftDeletes;

    protected $table = 'tournaments';

    protected $fillable = [
        'user_id',
        'name',
        'gender',
        'address',
        'stadium',
        'type_tournament',
        'number_player',
        'number_club',
        'max_player',
        'number_group',
        'number_knockout',
        'number_round',
        'score_win',
        'score_draw',
        'score_lose',
        'status',
        'charter',
        'introduce',
        'register_permission',
        'register_date',
    ];

    //----- Relationship -----//
}

app/Http/Controllers/Frontend/TournamentController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

/**
 * Class TournamentController
 * @package App\Http\Controllers
 */
class TournamentController extends Controller
{
    public function showFormCreate()
    {
        return view('frontend.tournaments.create');
    }

    public function showFormSearch()
    {
        return view('frontend.tournaments.search');
    }

    public function index()
    {
        return view('frontend.tournaments.index');
    }

    public function setting()
    {
        return view('frontend.tournaments.setting');
    }

    public function showStatusTournament()
    {
        return view('frontend.tournaments.status');
    }

    public function showListClub()
    {
        return view('frontend.tournaments.club');
    }

    public function showLeague()
    {
        return view('frontend.tournaments.sort-league');
    }

    public function showMatchPair()
    {
        return view('frontend.tournaments.sort-match-pair');
    }

    public function showSchedule()
    {
        return view('frontend.tournaments.schedule');
    }

    public function showGroupStage()
    {
        return view('frontend.tournaments.group-stage');
    }

    public function showKnockOut()
    {
        return view('frontend.tournaments.knockout');
    }

    public function showChart()
    {
        return view('frontend.tournaments.chart');
    }
}

resources/views/frontend/tournaments/includes/header.blade.php
<div class="info-user mb-5">
    <div class="row">
        <div class="col-4 col-md-2">
            <div class="avatar">
                <img src="{{asset('image/team.png')}}">
            </div>
        </div>
        <div class="col-8 col-md-4">
            <div class="email-user mb-2">
                <i class="fas fa-envelope"></i>
                lanta12a5@gmail.com
            </div>
            <div class="phone-number-user mb-2">
                <i class="fas fa-phone-alt"></i>
                0343900246
            </div>
            <div class="time-activity">
                <i class="fas fa-calendar-alt"></i>
                20:30 T3 HMG
            </div>
        </div>
        <div class="col-md-6">

        </div>
    </div>

</div>
<div class="container-fluid">
    <div class="list-tab-management">
        <ul class="nav nav-tabs" role="tab-list">
            <li class="nav-item">
                <a class="nav-link" href="#" role="tab">CHUNG</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" role="tab">VÒNG BẢNG</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" role="tab">VÒNG KNOCKOUT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" role="tab">BẢNG XẾP HẠNG</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"  href="#" role="tab">ĐỘI THI ĐẤU</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{route('user.tournaments.setting')}}" role="tab">CÀI ĐẶT</a>
            </li>
        </ul>
    </div>
</div>

resources/views/frontend/tournaments/includes/sidebar.blade.php
<div class="layout-sidenav-nav">
    <nav class="sb-sidenav sb-sidenav-dark">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <a class="nav-link nav-link-user collapsed" href="{{route('user.showManagementClub')}}">
                    <i class="fa fa-credit-card mr-2"></i>
                    Cấu hình giải đấu
                </a>
                <a class="nav-link nav-link-user collapsed" href="{{route('user.tournaments.status')}}">
                    <i class="fa fa-credit-card mr-2"></i>
                    Trạng thái
                </a>
                <a class="nav-link nav-link-user collapsed" href="{{route('user.showManagementClub')}}">
                    <i class="fa fa-credit-card mr-2"></i>
                    Danh sách đăng ký
                </a>
                <a class="nav-link nav-link-character collapsed" href="{{route('user.tournaments.clubs')}}">
                    <i class="fa fa-cog mr-2"></i>
                    Quản lý đội bóng
                </a>
                <a class="nav-link nav-link-deposit-and-payment collapsed" href="{{route('user.tournaments.showSchedule')}}">
                    <i class="fa fa-users mr-2"></i>
                    Quản lý lịch đấu
                </a>

                <a class="nav-link nav-link-various-setting collapsed" href="{{route('user.tournaments.sortLeague')}}">
                    <i class="far fa-futbol mr-2"></i>
                    Sắp xếp bảng đấu
                </a>

                <a class="nav-link nav-link-gacha collapsed" href="{{route('user.tournaments.sortMatchPair')}}">
                    <i class="far fa-chart-bar mr-2"></i>
                    Sắp xếp cặp đấu
                </a>
            </div>
        </div>
    </nav>
</div>